with open('.env', 'w', encoding='utf-8') as f:
    f.write("GEMINI_API_KEY=AIzaSyBHGTsWdopPuzmbjNV-WRJP8Cr44rupJjQ\n")
    f.write("GEMINI_MODEL=gemini-1.5-flash\n")
    f.write("\n")
    f.write("# Application Settings\n")
    f.write("APP_NAME=PDF to Excel Extraction\n")
    f.write("APP_VERSION=1.0.0\n")
    f.write("DEBUG=True\n")
    f.write("LOG_LEVEL=INFO\n")
    f.write("\n")
    f.write("# File Upload Settings\n")
    f.write("MAX_UPLOAD_SIZE_MB=50\n")
    f.write("ALLOWED_EXTENSIONS=.pdf\n")
    f.write("MAX_FILES_PER_UPLOAD=20\n")
    f.write("\n")
    f.write("# Storage Paths\n")
    f.write("UPLOAD_DIR=./uploads\n")
    f.write("OUTPUT_DIR=./outputs\n")
    f.write("LOG_DIR=./logs\n")
    f.write("\n")
    f.write("# CORS Settings\n")
    f.write("CORS_ORIGINS=http://localhost:5173,http://localhost:3000\n")
    f.write("\n")
    f.write("# OCR Settings\n")
    f.write("OCR_PROVIDER=gemini\n")
    f.write("FALLBACK_OCR=tesseract\n")
    f.write("OCR_TIMEOUT_SECONDS=30\n")
    f.write("MAX_RETRIES=3\n")
    f.write("\n")
    f.write("# Processing Settings\n")
    f.write("ENABLE_PREPROCESSING=True\n")
    f.write("IMAGE_DPI=300\n")
    f.write("PREPROCESSING_DENOISE=True\n")
    f.write("PREPROCESSING_CONTRAST=True\n")
    f.write("\n")
    f.write("# Rate Limiting\n")
    f.write("RATE_LIMIT_REQUESTS_PER_MINUTE=60\n")
    f.write("RATE_LIMIT_ENABLED=True\n")

print("✓ .env file created successfully")
