$lines = @(
    "GEMINI_API_KEY=AIzaSyBHGTsWdopPuzmbjNV-WRJP8Cr44rupJjQ",
    "GEMINI_MODEL=gemini-1.5-flash",
    "",
    "# Application Settings",
    "APP_NAME=PDF to Excel Extraction",
    "APP_VERSION=1.0.0",
    "DEBUG=True",
    "LOG_LEVEL=INFO",
    "",
    "# File Upload Settings",
    "MAX_UPLOAD_SIZE_MB=50",
    "ALLOWED_EXTENSIONS=.pdf",
    "MAX_FILES_PER_UPLOAD=20",
    "",
    "# Storage Paths",
    "UPLOAD_DIR=./uploads",
    "OUTPUT_DIR=./outputs",
    "LOG_DIR=./logs",
    "",
    "# CORS Settings (Frontend URL)",
    "CORS_ORIGINS=http://localhost:5173,http://localhost:3000",
    "",
    "# OCR Settings",
    "OCR_PROVIDER=gemini",
    "FALLBACK_OCR=tesseract",
    "OCR_TIMEOUT_SECONDS=30",
    "MAX_RETRIES=3",
    "",
    "# Processing Settings",
    "ENABLE_PREPROCESSING=True",
    "IMAGE_DPI=300",
    "PREPROCESSING_DENOISE=True",
    "PREPROCESSING_CONTRAST=True",
    "",
    "# Rate Limiting",
    "RATE_LIMIT_REQUESTS_PER_MINUTE=60",
    "RATE_LIMIT_ENABLED=True"
)

$lines | Set-Content -Path ".env" -Encoding UTF8
Write-Host "Successfully updated .env file with complete Gemini API key" -ForegroundColor Green
